# Generated by Django 3.1.1 on 2020-10-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('ceo', models.CharField(max_length=20)),
                ('tel_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('busin_num', models.IntegerField()),
                ('kakao_id', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
