# Generated by Django 3.1.1 on 2020-10-25 06:19

import contents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_agreement_announcement_faq_lecturer_profitshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitshare',
            name='image',
            field=models.ImageField(upload_to=contents.models.image_upload_to),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified time')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.lecturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
