# Generated by Django 3.1.1 on 2020-11-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20201025_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
