# Generated by Django 3.1.1 on 2020-11-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phnum', models.CharField(max_length=12, verbose_name='휴대폰번호')),
                ('pw', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_lecturer', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_kakao', models.BooleanField(default=False)),
                ('kakao_verify_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
