# Generated by Django 3.1.1 on 2020-11-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phnum', models.CharField(max_length=12, verbose_name='휴대폰번호')),
                ('pw', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프권한')),
                ('is_lecturer', models.BooleanField(default=False, verbose_name='멘토권한')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='관리자권한')),
                ('is_verified', models.BooleanField(default=False, verbose_name='본인인증여부')),
                ('is_kakao', models.BooleanField(default=False, verbose_name='카카오 로그인 회원 여부')),
                ('kakao_verify_id', models.CharField(max_length=100, verbose_name='카카오 토큰 아이디')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
